language: php

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

dist: trusty
sudo: false

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls

notifications:
  email: false