language: php

php:
    - 7.1
    - 7.0
    - 5.6
    - hhvm

dist: trusty
sudo: false

before_script:
    - composer install

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit

after_script:
    - vendor/bin/coveralls

notifications:
    email: false